@startuml class diagram

class Initilize


' Controlls the mechanical stuff, and the floor indicator
class ElevatorController


class LogicController


class OrderHandler

class ObsructionButton

class StoppButton

class FloorSensor

Initilize --> ElevatorController

LogicController ..> ObsructionButton

LogicController ..> OrderHandler

LogicController ..> StoppButton
LogicController ..> FloorSensor

LogicController --> ElevatorController





 
@enduml


