@startuml class diagram

class Initilize {
    +elevio_setup() : void
}


' Controlls the mechanical stuff, and the floor indicator
class elevio {
    +elevio_init() : void

    +elevio_motorDirection(MotorDirection dirn) : void
    +elevio_buttonLamp(int floor, ButtonType button, int value) : void
    +elevio_floorIndicator(int floor) : void
    +elevio_doorOpenLamp(int value) : void
    +elevio_stopLamp(int value) : void

    +elevio_callButton(int floor, ButtonType button) : int
    +elevio_floorSensor() : int
    +elevio_lastFloor() : int
    +elevio_stopButton() : int
    +elevio_obstruction() : int
}

class LogicController{
    -elevatorConditions : ElevatorConditions*
    -p_elevatorConditions : ElevatorConditions*
    -elevatorConditionArray[12] : int*
    -g_door_open_time : time_t
    -lastMotorDirection : MotorDirection

    +doorTimerFinnished : int
    +activeObstruction : int
    +stopPressed : int
    +currentState : ElevatorState
    +motorDirection : MotorDirection

    -makeElevatorDataArray(int* dataArray, const ElevatorConditions* p_conditions) : void
    -getNextState( int* dataArray ) : ElevatorState
    -runElevator(ElevatorState currentState, int is_new_state, ElevatorConditions* p_conditions) : void
    -doorHandling(int state_enter) : void

    +setupLogicController() : void
    +updateLogicController() : void
    +getCurrentState() : ElevatorState
    +getMotorDirection() : MotorDirection
}

class OrderHandler{
    +orderUpList[4] : int
    +orderDownList[4] : int

    +updateOrder(int currentFloor) : int
    +getOrder() : int
    +addOrderToList(int currentFloor, MotorDirection dir, int floorOrder, ButtonType buttonType,  int* upList, int* downList ): void
    +clearFloorFromList(int floor) : void
    +updateOrderHandler() : void
    +printList(const int* list) : void
}

Initilize --> elevio

LogicController ---> OrderHandler

LogicController --> elevio






@enduml


'returns -1 if the elevator is between floors'
+getLastFloor() : int