@startuml


Participant User

Participant Lights

User -> Button : Button pressed
activate Button


activate OrderHandler
Button -> OrderHandler : Forwarding input
deactivate Button

Lights <- OrderHandler : Turn on lights
activate Lights


OrderHandler -> LogicController : Next floor
activate LogicController
deactivate OrderHandler

LogicController -> Elevator : Run elevator
activate Elevator
deactivate LogicController
deactivate Elevator

User <- Lights : User sees lights
deactivate Lights

@enduml