@startuml state diagram

state Stop 
ElevatorRunning --> Stop : StoppButton pressed

state ElevatorRunning {
    [*] --> OnFloor

    OnFloor --> MovingUp 
    MovingUp --> OnFloor
    OnFloor --> MovingDown 
    MovingDown --> OnFloor
    OnFloor --> DoorOpen
    DoorOpen --> OnFloor
    Obstruction --> DoorOpen
    DoorOpen --> Obstruction

    Stop --> [H] : StoppButton released
}


@enduml